rewardPointsThreshold:
  onePoint: 50
  twoPoints: 100

#In-memory h2 Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.hbm2ddl.auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console.enabled: true
        
    
      
  
      
    


